### PR TITLE
[=] Fixed icons cache and optimizations in icon picture box

### PR DESCRIPTION
**Pull request by VoidVolker**
IconsCache -> static class, added dispose support
IconPictureBox - removed some useless code, added some optimizations

### CODE REVIEW

**Comment by VoidVolker** [comment]
@mkoertgen sorry, I reverted some parts of your changes and cleanup - because was far away from internet and wasn't able to download them. I hope you used some automatic tool for this :)

**Comment by mkoertgen** [comment]
No prob. Most of it was in deed automated.

**Comment by VoidVolker** [comment]
Ok, good. Any feedback or questions about code? What next? Shall I add some any new code or fix something?

**Comment by mkoertgen** [comment]
All good. I'll review the code and re-run ReSharper code cleanup. If any questions come up i will ask them here.

Maybe we should conclude on adding rotate/flip support also for the other controls. Would be glad if you could pick up on that (if you have time). Be sure to start from current develop before you start, if so.

Finally let's merge to master and publish the new version. Expect that to happen in a few days.

**Comment by VoidVolker** [comment]
Ok, I'll add rotate/flip for other controls.

**Pull request merged**
